Removed -z from curl, verified if json2tsv can run and added NE scale 1:10m.

diff --git a/prepublish b/prepublish
--- a/prepublish
+++ b/prepublish
@@ -4,7 +4,7 @@ rm -rvf world
 
 world_shp() {
   mkdir -p build
-  curl -z build/ne_$1_admin_0_countries.zip -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
+  curl -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
   unzip -od build build/ne_$1_admin_0_countries.zip
   chmod a-x build/ne_$1_admin_0_countries.*
 }
@@ -18,12 +18,18 @@ world() {
         | geostitch -n) \
     | topomerge land=countries \
     > world/$1.json
-  shp2json -n build/ne_$1_admin_0_countries.shp \
-    | ndjson-map 'd.properties' \
-    | ndjson-sort 'a.iso_a3.localeCompare(b.iso_a3)' \
-    | json2tsv -n \
-    > world/$1.tsv
+
+  if ! [ -x "$(command -v json2tsv)" ]; then
+    echo "Error: json2tsv was not found. world/$1.tsv not created." >&2
+  else
+    shp2json -n build/ne_$1_admin_0_countries.shp \
+      | ndjson-map 'd.properties' \
+      | ndjson-sort 'a.iso_a3.localeCompare(b.iso_a3)' \
+      | json2tsv -n \
+      > world/$1.tsv
+  fi
 }
 
 world 110m
 world 50m
+world 10m
